// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.cache.purgeActor
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::types::string::Did;
use jacquard_derive::{IntoStatic, lexicon};
use serde::{Serialize, Deserialize};

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct PurgeActor<'a> {
    #[serde(borrow)]
    pub did: Did<'a>,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct PurgeActorOutput<'a> {}
/// Response type for dev.blooym.porxie.cache.purgeActor
pub struct PurgeActorResponse;
impl jacquard_common::xrpc::XrpcResp for PurgeActorResponse {
    const NSID: &'static str = "dev.blooym.porxie.cache.purgeActor";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = PurgeActorOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for PurgeActor<'a> {
    const NSID: &'static str = "dev.blooym.porxie.cache.purgeActor";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = PurgeActorResponse;
}

/// Endpoint type for dev.blooym.porxie.cache.purgeActor
pub struct PurgeActorRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PurgeActorRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.cache.purgeActor";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = PurgeActor<'de>;
    type Response = PurgeActorResponse;
}

pub mod purge_actor_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type
pub struct PurgeActorBuilder<'a, S: purge_actor_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Did<'a>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> PurgeActor<'a> {
    /// Create a new builder for this type
    pub fn new() -> PurgeActorBuilder<'a, purge_actor_state::Empty> {
        PurgeActorBuilder::new()
    }
}

impl<'a> PurgeActorBuilder<'a, purge_actor_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        PurgeActorBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> PurgeActorBuilder<'a, S>
where
    S: purge_actor_state::State,
    S::Did: purge_actor_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<'a>>,
    ) -> PurgeActorBuilder<'a, purge_actor_state::SetDid<S>> {
        self._fields.0 = Option::Some(value.into());
        PurgeActorBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> PurgeActorBuilder<'a, S>
where
    S: purge_actor_state::State,
    S::Did: purge_actor_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> PurgeActor<'a> {
        PurgeActor {
            did: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> PurgeActor<'a> {
        PurgeActor {
            did: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}