// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.cache.purgeBlob
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::Cid;
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct PurgeBlob<S: BosStr = DefaultStr> {
    pub cid: Cid<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct PurgeBlobOutput<S: BosStr = DefaultStr> {
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum PurgeBlobError {
    /// The provided CID was malformed or does not conform to specification.
    #[serde(rename = "MalformedCid")]
    MalformedCid(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other { error: SmolStr, message: Option<SmolStr> },
}

impl core::fmt::Display for PurgeBlobError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::MalformedCid(msg) => {
                write!(f, "MalformedCid")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}

/** Response marker for the `dev.blooym.porxie.cache.purgeBlob` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `PurgeBlobOutput<S>` for this endpoint.*/
pub struct PurgeBlobResponse;
impl jacquard_common::xrpc::XrpcResp for PurgeBlobResponse {
    const NSID: &'static str = "dev.blooym.porxie.cache.purgeBlob";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = PurgeBlobOutput<S>;
    type Err = PurgeBlobError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for PurgeBlob<S> {
    const NSID: &'static str = "dev.blooym.porxie.cache.purgeBlob";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = PurgeBlobResponse;
}

/** Endpoint marker for the `dev.blooym.porxie.cache.purgeBlob` procedure.

Path: `/xrpc/dev.blooym.porxie.cache.purgeBlob`. The request payload type is `PurgeBlob<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct PurgeBlobRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PurgeBlobRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.cache.purgeBlob";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = PurgeBlob<S>;
    type Response = PurgeBlobResponse;
}

pub mod purge_blob_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Cid;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Cid = Unset;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCid<St> {}
    impl<St: State> State for SetCid<St> {
        type Cid = Set<members::cid>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `cid` field
        pub struct cid(());
    }
}

/// Builder for constructing an instance of this type.
pub struct PurgeBlobBuilder<St: purge_blob_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Cid<S>>,),
    _type: PhantomData<fn() -> S>,
}

impl PurgeBlob<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> PurgeBlobBuilder<purge_blob_state::Empty, DefaultStr> {
        PurgeBlobBuilder::new()
    }
}

impl<S: BosStr> PurgeBlob<S> {
    /// Create a new builder for this type
    pub fn builder() -> PurgeBlobBuilder<purge_blob_state::Empty, S> {
        PurgeBlobBuilder::builder()
    }
}

impl PurgeBlobBuilder<purge_blob_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        PurgeBlobBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> PurgeBlobBuilder<purge_blob_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        PurgeBlobBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PurgeBlobBuilder<St, S>
where
    St: purge_blob_state::State,
    St::Cid: purge_blob_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<Cid<S>>,
    ) -> PurgeBlobBuilder<purge_blob_state::SetCid<St>, S> {
        self._fields.0 = Option::Some(value.into());
        PurgeBlobBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> PurgeBlobBuilder<St, S>
where
    St: purge_blob_state::State,
    St::Cid: purge_blob_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> PurgeBlob<S> {
        PurgeBlob {
            cid: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> PurgeBlob<S> {
        PurgeBlob {
            cid: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}