// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.cache.purgeAll
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct PurgeAll<S: BosStr = DefaultStr> {
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct PurgeAllOutput<S: BosStr = DefaultStr> {
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/** Response marker for the `dev.blooym.porxie.cache.purgeAll` procedure.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `PurgeAllOutput<S>` for this endpoint.*/
pub struct PurgeAllResponse;
impl jacquard_common::xrpc::XrpcResp for PurgeAllResponse {
    const NSID: &'static str = "dev.blooym.porxie.cache.purgeAll";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = PurgeAllOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for PurgeAll<S> {
    const NSID: &'static str = "dev.blooym.porxie.cache.purgeAll";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = PurgeAllResponse;
}

/** Endpoint marker for the `dev.blooym.porxie.cache.purgeAll` procedure.

Path: `/xrpc/dev.blooym.porxie.cache.purgeAll`. The request payload type is `PurgeAll<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct PurgeAllRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PurgeAllRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.cache.purgeAll";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<S: BosStr> = PurgeAll<S>;
    type Response = PurgeAllResponse;
}