// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.cache.purgeAll
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_derive::{IntoStatic, lexicon};
use serde::{Serialize, Deserialize};

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct PurgeAll<'a> {}

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct PurgeAllOutput<'a> {}
/// Response type for dev.blooym.porxie.cache.purgeAll
pub struct PurgeAllResponse;
impl jacquard_common::xrpc::XrpcResp for PurgeAllResponse {
    const NSID: &'static str = "dev.blooym.porxie.cache.purgeAll";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = PurgeAllOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for PurgeAll<'a> {
    const NSID: &'static str = "dev.blooym.porxie.cache.purgeAll";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = PurgeAllResponse;
}

/// Endpoint type for dev.blooym.porxie.cache.purgeAll
pub struct PurgeAllRequest;
impl jacquard_common::xrpc::XrpcEndpoint for PurgeAllRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.cache.purgeAll";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = PurgeAll<'de>;
    type Response = PurgeAllResponse;
}