[package]
name = "porxie"
description = "A correct and efficient ATProtocol blob proxy for secure content delivery."
authors = ["Blooym"]
repository = "https://codeberg.org/Blooym/porxie"
homepage = "https://codeberg.org/Blooym/porxie/src/branch/main/README.md"
documentation = "https://codeberg.org/Blooym/porxie/src/branch/main/README.md"
license = "AGPL-3.0-or-later"
version = "0.3.3"
edition = "2024"

[lints.clippy]
unwrap_used = "deny"
panic = "deny"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
anyhow = { version = "1.0.102", features = ["std"], default-features = false }
axum = { version = "0.8.9", features = [
    "http1",
    "http2",
    "json",
    "matched-path",
    "tokio",
    "tower-log",
    "tracing",
], default-features = false }
axum-extra = { version = "0.12.6", features = [
    "typed-header",
    "tracing",
], default-features = false }
bytes = { version = "1.11.1", features = ["std"], default-features = false }
bytesize = { version = "2.4.0", features = ["std"], default-features = false }
cid = { version = "0.11.3", features = ["std"], default-features = false }
clap = { version = "4.6.1", features = [
    "color",
    "derive",
    "env",
    "error-context",
    "help",
    "std",
    "suggestions",
    "usage",
], default-features = false }
dotenvy = { version = "0.15.7", default-features = false }
futures-util = { version = "0.3.32", default-features = false }
humantime = { version = "2.3.0", default-features = false }
jacquard-axum = { version = "0.12.0", default-features = false, features = [
    "tracing",
] }
jacquard-common = {  version = "0.12.0", default-features = false }
jacquard-identity = { version = "0.12.0", features = ["tracing"] }
jemallocator = "0.5.4"
porxie-lexgen = { path = "../porxie-lexgen", default-features = false, features = [
    "dev_blooym",
] }
porxie-mediautil = { path = "../porxie-mediautil", default-features = false, features = [
    "video-metadata",
    "image-metadata",
] }
moka = { version = "0.12.15", features = [
    "future",
    "logging",
], default-features = false }
multihash-codetable = { version = "0.2.2", features = [
    "sha2",
    # "blake3", # if it ever gets added to the spec.
    "std",
], default-features = false }
reqwest = { version = "0.12.28", default-features = false, features = [
    "http2",
    "system-proxy",
    "stream",
    "socks",
    "rustls-tls",
    "gzip",
    "brotli",
    "zstd",
    "deflate",
] }
serde = { version = "1.0.228", features = [
    "derive",
    "std",
], default-features = false }
serde_json = "1.0.150"
subtle = { version = "2.6.1", default-features = false, features = ["std"] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
tokio = { version = "1.52.3", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "net",
] }
tower-http = { version = "0.7.0", features = [
    "catch-panic",
    "normalize-path",
    "trace",
    "timeout",
    "tracing",
    "cors",
], default-features = false }
tracing = { version = "0.1.44", features = [
    "attributes",
    "std",
], default-features = false }
tracing-subscriber = { version = "0.3.23", features = [
    "ansi",
    "env-filter",
    "fmt",
    "parking_lot",
    "json",
    "smallvec",
    "std",
    "tracing",
    "tracing-log",
], default-features = false }
url = { version = "2.5.8", default-features = false }
