[package]
name = "porxie"
description = "A correct and efficient ATProto blob proxy for secure content delivery."
authors = ["Blooym"]
repository = "https://codeberg.org/Blooym/porxie"
homepage = "https://codeberg.org/Blooym/porxie/src/branch/main/README.md"
documentation = "https://codeberg.org/Blooym/porxie/src/branch/main/README.md"
license = "AGPL-3.0-or-later"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
anyhow = { version = "1.0.102", features = ["std"], default-features = false }
axum = { version = "0.8.8", features = [
    "http1",
    "http2",
    "json",
    "matched-path",
    "tokio",
    "tower-log",
    "tracing",
], default-features = false }
axum-extra = { version = "0.12.5", features = [
    "typed-header",
    "tracing",
], default-features = false }
bytes = { version = "1.11.1", features = ["std"], default-features = false }
bytesize = { version = "2.3.1", features = ["std"], default-features = false }
cid = { version = "0.11.1", features = ["std"], default-features = false }
clap = { version = "4.5.60", features = [
    "color",
    "derive",
    "env",
    "error-context",
    "help",
    "std",
    "suggestions",
    "usage",
], default-features = false }
dotenvy = { version = "0.15.7", default-features = false }
futures-util = { version = "0.3.32", default-features = false }
humantime = { version = "2.3.0", default-features = false }
infer = { version = "0.19.0", default-features = false, features = ["std"] }
jacquard-common = { version = "0.9.5", default-features = false }
jacquard-identity = { version = "0.9.5", features = ["tracing"] }
json-subscriber = { version = "0.2.8", default-features = false, features = [
    "tracing-log",
    "env-filter",
] }
mime = { version = "0.3.17", default-features = false }
tracing = { version = "0.1.44", features = ["std"], default-features = false }
moka = { version = "0.12.14", features = [
    "future",
    "logging",
], default-features = false }
multihash-codetable = { version = "0.2.1", features = [
    "sha2",
    "blake3",
    "std",
], default-features = false }
reqwest = { version = "0.12.28", default-features = false, features = [
    "http2",
    "system-proxy",
    "stream",
    "socks",
    "rustls-tls",
    "gzip",
    "brotli",
    "zstd",
    "deflate",
] }
serde = { version = "1.0.228", features = [
    "derive",
    "std",
], default-features = false }
sysinfo = { version = "0.38.4", default-features = false, features = [
    "system",
] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
tokio = { version = "1.50.0", default-features = false, features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "net",
] }
tower-http = { version = "0.6.8", features = [
    "catch-panic",
    "normalize-path",
    "trace",
    "timeout",
    "tracing",
], default-features = false }
tracing-subscriber = { version = "0.3.22", features = [
    "ansi",
    "env-filter",
    "fmt",
    "parking_lot",
    "smallvec",
    "std",
    "tracing",
    "tracing-log",
], default-features = false }
