// @generated by jacquard-lexicon. DO NOT EDIT.
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

//! Generated bindings for the `dev.blooym.porxie` Lexicon namespace/module.
pub mod cache;
pub mod get_blob;
pub mod get_blob_metadata;
pub mod get_blob_policy;