// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.getBlobPolicy
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Did, Cid};
use jacquard_common::types::value::Data;
use jacquard_derive::IntoStatic;
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::dev_blooym::porxie::get_blob_policy;
/// Blob is allowed to be served.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Allowed<S: BosStr = DefaultStr> {
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

/// Blob is not allowed to be served.

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct Forbidden<S: BosStr = DefaultStr> {
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetBlobPolicy<S: BosStr = DefaultStr> {
    pub cid: Cid<S>,
    pub did: Did<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetBlobPolicyOutput<S: BosStr = DefaultStr> {
    pub policy: GetBlobPolicyOutputPolicy<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(tag = "$type", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub enum GetBlobPolicyOutputPolicy<S: BosStr = DefaultStr> {
    #[serde(rename = "dev.blooym.porxie.getBlobPolicy#allowed")]
    Allowed(Box<get_blob_policy::Allowed<S>>),
    #[serde(rename = "dev.blooym.porxie.getBlobPolicy#forbidden")]
    Forbidden(Box<get_blob_policy::Forbidden<S>>),
}

impl<S: BosStr> LexiconSchema for Allowed<S> {
    fn nsid() -> &'static str {
        "dev.blooym.porxie.getBlobPolicy"
    }
    fn def_name() -> &'static str {
        "allowed"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_dev_blooym_porxie_getBlobPolicy()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for Forbidden<S> {
    fn nsid() -> &'static str {
        "dev.blooym.porxie.getBlobPolicy"
    }
    fn def_name() -> &'static str {
        "forbidden"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_dev_blooym_porxie_getBlobPolicy()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

/** Response marker for the `dev.blooym.porxie.getBlobPolicy` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetBlobPolicyOutput<S>` for this endpoint.*/
pub struct GetBlobPolicyResponse;
impl jacquard_common::xrpc::XrpcResp for GetBlobPolicyResponse {
    const NSID: &'static str = "dev.blooym.porxie.getBlobPolicy";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetBlobPolicyOutput<S>;
    type Err = jacquard_common::xrpc::GenericError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetBlobPolicy<S> {
    const NSID: &'static str = "dev.blooym.porxie.getBlobPolicy";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetBlobPolicyResponse;
}

/** Endpoint marker for the `dev.blooym.porxie.getBlobPolicy` query.

Path: `/xrpc/dev.blooym.porxie.getBlobPolicy`. The request payload type is `GetBlobPolicy<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetBlobPolicyRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetBlobPolicyRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.getBlobPolicy";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetBlobPolicy<S>;
    type Response = GetBlobPolicyResponse;
}

fn lexicon_doc_dev_blooym_porxie_getBlobPolicy() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("dev.blooym.porxie.getBlobPolicy"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("allowed"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static("Blob is allowed to be served."),
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("forbidden"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static("Blob is not allowed to be served."),
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::XrpcQuery(LexXrpcQuery {
                    parameters: Some(
                        LexXrpcQueryParameter::Params(LexXrpcParameters {
                            required: Some(
                                vec![SmolStr::new_static("did"), SmolStr::new_static("cid")],
                            ),
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = BTreeMap::new();
                                map.insert(
                                    SmolStr::new_static("cid"),
                                    LexXrpcParametersProperty::String(LexString {
                                        format: Some(LexStringFormat::Cid),
                                        ..Default::default()
                                    }),
                                );
                                map.insert(
                                    SmolStr::new_static("did"),
                                    LexXrpcParametersProperty::String(LexString {
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                );
                                map
                            },
                            ..Default::default()
                        }),
                    ),
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod get_blob_policy_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Cid;
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Cid = Unset;
        type Did = Unset;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCid<St> {}
    impl<St: State> State for SetCid<St> {
        type Cid = Set<members::cid>;
        type Did = St::Did;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type Cid = St::Cid;
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `cid` field
        pub struct cid(());
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetBlobPolicyBuilder<
    St: get_blob_policy_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Cid<S>>, Option<Did<S>>),
    _type: PhantomData<fn() -> S>,
}

impl GetBlobPolicy<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetBlobPolicyBuilder<get_blob_policy_state::Empty, DefaultStr> {
        GetBlobPolicyBuilder::new()
    }
}

impl<S: BosStr> GetBlobPolicy<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetBlobPolicyBuilder<get_blob_policy_state::Empty, S> {
        GetBlobPolicyBuilder::builder()
    }
}

impl GetBlobPolicyBuilder<get_blob_policy_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetBlobPolicyBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetBlobPolicyBuilder<get_blob_policy_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetBlobPolicyBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetBlobPolicyBuilder<St, S>
where
    St: get_blob_policy_state::State,
    St::Cid: get_blob_policy_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<Cid<S>>,
    ) -> GetBlobPolicyBuilder<get_blob_policy_state::SetCid<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetBlobPolicyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetBlobPolicyBuilder<St, S>
where
    St: get_blob_policy_state::State,
    St::Did: get_blob_policy_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<S>>,
    ) -> GetBlobPolicyBuilder<get_blob_policy_state::SetDid<St>, S> {
        self._fields.1 = Option::Some(value.into());
        GetBlobPolicyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetBlobPolicyBuilder<St, S>
where
    St: get_blob_policy_state::State,
    St::Cid: get_blob_policy_state::IsSet,
    St::Did: get_blob_policy_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetBlobPolicy<S> {
        GetBlobPolicy {
            cid: self._fields.0.unwrap(),
            did: self._fields.1.unwrap(),
        }
    }
}