// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.getBlobMetadata
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::{CowStr, BosStr, DefaultStr, FromStaticStr};

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::deps::smol_str::SmolStr;
use jacquard_common::types::string::{Did, Cid};
use jacquard_common::types::value::Data;
use jacquard_derive::{IntoStatic, open_union};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::dev_blooym::porxie::get_blob_metadata;

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct AspectRatio<S: BosStr = DefaultStr> {
    pub height: i64,
    pub width: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct ImageData<S: BosStr = DefaultStr> {
    pub aspect_ratio: get_blob_metadata::AspectRatio<S>,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetBlobMetadata<S: BosStr = DefaultStr> {
    pub cid: Cid<S>,
    pub did: Did<S>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct GetBlobMetadataOutput<S: BosStr = DefaultStr> {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub content_type: Option<S>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<GetBlobMetadataOutputData<S>>,
    pub size: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}


#[open_union]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(tag = "$type", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub enum GetBlobMetadataOutputData<S: BosStr = DefaultStr> {
    #[serde(rename = "dev.blooym.porxie.getBlobMetadata#imageData")]
    ImageData(Box<get_blob_metadata::ImageData<S>>),
    #[serde(rename = "dev.blooym.porxie.getBlobMetadata#videoData")]
    VideoData(Box<get_blob_metadata::VideoData<S>>),
}


#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic
)]

#[serde(tag = "error", content = "message")]
pub enum GetBlobMetadataError {
    /// The provided CID was malformed or does not conform to specification.
    #[serde(rename = "MalformedCid")]
    MalformedCid(Option<SmolStr>),
    #[serde(rename = "BlobCidMismatch")]
    BlobCidMismatch(Option<SmolStr>),
    #[serde(rename = "BlobFetchFailed")]
    BlobFetchFailed(Option<SmolStr>),
    #[serde(rename = "BlobForbiddenType")]
    BlobForbiddenType(Option<SmolStr>),
    #[serde(rename = "BlobNotFound")]
    BlobNotFound(Option<SmolStr>),
    #[serde(rename = "BlobTooLarge")]
    BlobTooLarge(Option<SmolStr>),
    #[serde(rename = "CannotResolve")]
    CannotResolve(Option<SmolStr>),
    #[serde(rename = "CidUnsupported")]
    CidUnsupported(Option<SmolStr>),
    #[serde(rename = "PolicyForbidden")]
    PolicyForbidden(Option<SmolStr>),
    /// Catch-all for unknown error codes.
    #[serde(untagged)]
    Other { error: SmolStr, message: Option<SmolStr> },
}

impl core::fmt::Display for GetBlobMetadataError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::MalformedCid(msg) => {
                write!(f, "MalformedCid")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobCidMismatch(msg) => {
                write!(f, "BlobCidMismatch")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobFetchFailed(msg) => {
                write!(f, "BlobFetchFailed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobForbiddenType(msg) => {
                write!(f, "BlobForbiddenType")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobNotFound(msg) => {
                write!(f, "BlobNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobTooLarge(msg) => {
                write!(f, "BlobTooLarge")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::CannotResolve(msg) => {
                write!(f, "CannotResolve")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::CidUnsupported(msg) => {
                write!(f, "CidUnsupported")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::PolicyForbidden(msg) => {
                write!(f, "PolicyForbidden")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Other { error, message } => {
                write!(f, "{}", error)?;
                if let Some(msg) = message {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
        }
    }
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase", bound(deserialize = "S: Deserialize<'de> + BosStr"))]
pub struct VideoData<S: BosStr = DefaultStr> {
    pub aspect_ratio: get_blob_metadata::AspectRatio<S>,
    pub duration_ms: i64,
    #[serde(flatten, default, skip_serializing_if = "Option::is_none")]
    pub extra_data: Option<BTreeMap<SmolStr, Data<S>>>,
}

impl<S: BosStr> LexiconSchema for AspectRatio<S> {
    fn nsid() -> &'static str {
        "dev.blooym.porxie.getBlobMetadata"
    }
    fn def_name() -> &'static str {
        "aspectRatio"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_dev_blooym_porxie_getBlobMetadata()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.height;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("height"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        {
            let value = &self.width;
            if *value < 1i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("width"),
                    min: 1i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

impl<S: BosStr> LexiconSchema for ImageData<S> {
    fn nsid() -> &'static str {
        "dev.blooym.porxie.getBlobMetadata"
    }
    fn def_name() -> &'static str {
        "imageData"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_dev_blooym_porxie_getBlobMetadata()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

/** Response marker for the `dev.blooym.porxie.getBlobMetadata` query.

Implements `jacquard_common::xrpc::XrpcResp`; successful bodies decode as `Self::Output<S>`, which is `GetBlobMetadataOutput<S>` for this endpoint.*/
pub struct GetBlobMetadataResponse;
impl jacquard_common::xrpc::XrpcResp for GetBlobMetadataResponse {
    const NSID: &'static str = "dev.blooym.porxie.getBlobMetadata";
    const ENCODING: &'static str = "application/json";
    type Output<S: BosStr> = GetBlobMetadataOutput<S>;
    type Err = GetBlobMetadataError;
}

impl<S: BosStr> jacquard_common::xrpc::XrpcRequest for GetBlobMetadata<S> {
    const NSID: &'static str = "dev.blooym.porxie.getBlobMetadata";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetBlobMetadataResponse;
}

/** Endpoint marker for the `dev.blooym.porxie.getBlobMetadata` query.

Path: `/xrpc/dev.blooym.porxie.getBlobMetadata`. The request payload type is `GetBlobMetadata<S>`; send that request with `jacquard::Client` or use this marker through lower-level `XrpcEndpoint` APIs.*/
pub struct GetBlobMetadataRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetBlobMetadataRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.getBlobMetadata";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<S: BosStr> = GetBlobMetadata<S>;
    type Response = GetBlobMetadataResponse;
}

impl<S: BosStr> LexiconSchema for VideoData<S> {
    fn nsid() -> &'static str {
        "dev.blooym.porxie.getBlobMetadata"
    }
    fn def_name() -> &'static str {
        "videoData"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_dev_blooym_porxie_getBlobMetadata()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        {
            let value = &self.duration_ms;
            if *value < 0i64 {
                return Err(ConstraintError::Minimum {
                    path: ValidationPath::from_field("duration_ms"),
                    min: 0i64,
                    actual: *value,
                });
            }
        }
        Ok(())
    }
}

pub mod aspect_ratio_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Height;
        type Width;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Height = Unset;
        type Width = Unset;
    }
    ///State transition - sets the `height` field to Set
    pub struct SetHeight<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetHeight<St> {}
    impl<St: State> State for SetHeight<St> {
        type Height = Set<members::height>;
        type Width = St::Width;
    }
    ///State transition - sets the `width` field to Set
    pub struct SetWidth<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetWidth<St> {}
    impl<St: State> State for SetWidth<St> {
        type Height = St::Height;
        type Width = Set<members::width>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `height` field
        pub struct height(());
        ///Marker type for the `width` field
        pub struct width(());
    }
}

/// Builder for constructing an instance of this type.
pub struct AspectRatioBuilder<St: aspect_ratio_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<i64>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl AspectRatio<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> AspectRatioBuilder<aspect_ratio_state::Empty, DefaultStr> {
        AspectRatioBuilder::new()
    }
}

impl<S: BosStr> AspectRatio<S> {
    /// Create a new builder for this type
    pub fn builder() -> AspectRatioBuilder<aspect_ratio_state::Empty, S> {
        AspectRatioBuilder::builder()
    }
}

impl AspectRatioBuilder<aspect_ratio_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        AspectRatioBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> AspectRatioBuilder<aspect_ratio_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        AspectRatioBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AspectRatioBuilder<St, S>
where
    St: aspect_ratio_state::State,
    St::Height: aspect_ratio_state::IsUnset,
{
    /// Set the `height` field (required)
    pub fn height(
        mut self,
        value: impl Into<i64>,
    ) -> AspectRatioBuilder<aspect_ratio_state::SetHeight<St>, S> {
        self._fields.0 = Option::Some(value.into());
        AspectRatioBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AspectRatioBuilder<St, S>
where
    St: aspect_ratio_state::State,
    St::Width: aspect_ratio_state::IsUnset,
{
    /// Set the `width` field (required)
    pub fn width(
        mut self,
        value: impl Into<i64>,
    ) -> AspectRatioBuilder<aspect_ratio_state::SetWidth<St>, S> {
        self._fields.1 = Option::Some(value.into());
        AspectRatioBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> AspectRatioBuilder<St, S>
where
    St: aspect_ratio_state::State,
    St::Height: aspect_ratio_state::IsSet,
    St::Width: aspect_ratio_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> AspectRatio<S> {
        AspectRatio {
            height: self._fields.0.unwrap(),
            width: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> AspectRatio<S> {
        AspectRatio {
            height: self._fields.0.unwrap(),
            width: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

fn lexicon_doc_dev_blooym_porxie_getBlobMetadata() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("dev.blooym.porxie.getBlobMetadata"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("aspectRatio"),
                LexUserType::Object(LexObject {
                    required: Some(
                        vec![SmolStr::new_static("width"), SmolStr::new_static("height")],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("height"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(1i64),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("width"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(1i64),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("imageData"),
                LexUserType::Object(LexObject {
                    required: Some(vec![SmolStr::new_static("aspectRatio")]),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("aspectRatio"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static("#aspectRatio"),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::XrpcQuery(LexXrpcQuery {
                    parameters: Some(
                        LexXrpcQueryParameter::Params(LexXrpcParameters {
                            required: Some(
                                vec![SmolStr::new_static("did"), SmolStr::new_static("cid")],
                            ),
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = BTreeMap::new();
                                map.insert(
                                    SmolStr::new_static("cid"),
                                    LexXrpcParametersProperty::String(LexString {
                                        format: Some(LexStringFormat::Cid),
                                        ..Default::default()
                                    }),
                                );
                                map.insert(
                                    SmolStr::new_static("did"),
                                    LexXrpcParametersProperty::String(LexString {
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                );
                                map
                            },
                            ..Default::default()
                        }),
                    ),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("videoData"),
                LexUserType::Object(LexObject {
                    required: Some(
                        vec![
                            SmolStr::new_static("aspectRatio"),
                            SmolStr::new_static("durationMs")
                        ],
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("aspectRatio"),
                            LexObjectProperty::Ref(LexRef {
                                r#ref: CowStr::new_static("#aspectRatio"),
                                ..Default::default()
                            }),
                        );
                        map.insert(
                            SmolStr::new_static("durationMs"),
                            LexObjectProperty::Integer(LexInteger {
                                minimum: Some(0i64),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod image_data_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type AspectRatio;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type AspectRatio = Unset;
    }
    ///State transition - sets the `aspect_ratio` field to Set
    pub struct SetAspectRatio<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetAspectRatio<St> {}
    impl<St: State> State for SetAspectRatio<St> {
        type AspectRatio = Set<members::aspect_ratio>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `aspect_ratio` field
        pub struct aspect_ratio(());
    }
}

/// Builder for constructing an instance of this type.
pub struct ImageDataBuilder<St: image_data_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<get_blob_metadata::AspectRatio<S>>,),
    _type: PhantomData<fn() -> S>,
}

impl ImageData<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> ImageDataBuilder<image_data_state::Empty, DefaultStr> {
        ImageDataBuilder::new()
    }
}

impl<S: BosStr> ImageData<S> {
    /// Create a new builder for this type
    pub fn builder() -> ImageDataBuilder<image_data_state::Empty, S> {
        ImageDataBuilder::builder()
    }
}

impl ImageDataBuilder<image_data_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        ImageDataBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> ImageDataBuilder<image_data_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        ImageDataBuilder {
            _state: PhantomData,
            _fields: (None,),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ImageDataBuilder<St, S>
where
    St: image_data_state::State,
    St::AspectRatio: image_data_state::IsUnset,
{
    /// Set the `aspectRatio` field (required)
    pub fn aspect_ratio(
        mut self,
        value: impl Into<get_blob_metadata::AspectRatio<S>>,
    ) -> ImageDataBuilder<image_data_state::SetAspectRatio<St>, S> {
        self._fields.0 = Option::Some(value.into());
        ImageDataBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> ImageDataBuilder<St, S>
where
    St: image_data_state::State,
    St::AspectRatio: image_data_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> ImageData<S> {
        ImageData {
            aspect_ratio: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> ImageData<S> {
        ImageData {
            aspect_ratio: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}

pub mod get_blob_metadata_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Cid;
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Cid = Unset;
        type Did = Unset;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetCid<St> {}
    impl<St: State> State for SetCid<St> {
        type Cid = Set<members::cid>;
        type Did = St::Did;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDid<St> {}
    impl<St: State> State for SetDid<St> {
        type Cid = St::Cid;
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `cid` field
        pub struct cid(());
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type.
pub struct GetBlobMetadataBuilder<
    St: get_blob_metadata_state::State,
    S: BosStr = DefaultStr,
> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<Cid<S>>, Option<Did<S>>),
    _type: PhantomData<fn() -> S>,
}

impl GetBlobMetadata<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> GetBlobMetadataBuilder<get_blob_metadata_state::Empty, DefaultStr> {
        GetBlobMetadataBuilder::new()
    }
}

impl<S: BosStr> GetBlobMetadata<S> {
    /// Create a new builder for this type
    pub fn builder() -> GetBlobMetadataBuilder<get_blob_metadata_state::Empty, S> {
        GetBlobMetadataBuilder::builder()
    }
}

impl GetBlobMetadataBuilder<get_blob_metadata_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        GetBlobMetadataBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> GetBlobMetadataBuilder<get_blob_metadata_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        GetBlobMetadataBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetBlobMetadataBuilder<St, S>
where
    St: get_blob_metadata_state::State,
    St::Cid: get_blob_metadata_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<Cid<S>>,
    ) -> GetBlobMetadataBuilder<get_blob_metadata_state::SetCid<St>, S> {
        self._fields.0 = Option::Some(value.into());
        GetBlobMetadataBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetBlobMetadataBuilder<St, S>
where
    St: get_blob_metadata_state::State,
    St::Did: get_blob_metadata_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<S>>,
    ) -> GetBlobMetadataBuilder<get_blob_metadata_state::SetDid<St>, S> {
        self._fields.1 = Option::Some(value.into());
        GetBlobMetadataBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> GetBlobMetadataBuilder<St, S>
where
    St: get_blob_metadata_state::State,
    St::Cid: get_blob_metadata_state::IsSet,
    St::Did: get_blob_metadata_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> GetBlobMetadata<S> {
        GetBlobMetadata {
            cid: self._fields.0.unwrap(),
            did: self._fields.1.unwrap(),
        }
    }
}

pub mod video_data_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type AspectRatio;
        type DurationMs;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type AspectRatio = Unset;
        type DurationMs = Unset;
    }
    ///State transition - sets the `aspect_ratio` field to Set
    pub struct SetAspectRatio<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetAspectRatio<St> {}
    impl<St: State> State for SetAspectRatio<St> {
        type AspectRatio = Set<members::aspect_ratio>;
        type DurationMs = St::DurationMs;
    }
    ///State transition - sets the `duration_ms` field to Set
    pub struct SetDurationMs<St: State = Empty>(PhantomData<fn() -> St>);
    impl<St: State> sealed::Sealed for SetDurationMs<St> {}
    impl<St: State> State for SetDurationMs<St> {
        type AspectRatio = St::AspectRatio;
        type DurationMs = Set<members::duration_ms>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `aspect_ratio` field
        pub struct aspect_ratio(());
        ///Marker type for the `duration_ms` field
        pub struct duration_ms(());
    }
}

/// Builder for constructing an instance of this type.
pub struct VideoDataBuilder<St: video_data_state::State, S: BosStr = DefaultStr> {
    _state: PhantomData<fn() -> St>,
    _fields: (Option<get_blob_metadata::AspectRatio<S>>, Option<i64>),
    _type: PhantomData<fn() -> S>,
}

impl VideoData<DefaultStr> {
    /// Create a new builder for this type, using the default string type (DefaultStr = SmolStr) if needed
    pub fn new() -> VideoDataBuilder<video_data_state::Empty, DefaultStr> {
        VideoDataBuilder::new()
    }
}

impl<S: BosStr> VideoData<S> {
    /// Create a new builder for this type
    pub fn builder() -> VideoDataBuilder<video_data_state::Empty, S> {
        VideoDataBuilder::builder()
    }
}

impl VideoDataBuilder<video_data_state::Empty, DefaultStr> {
    /// Create a new builder with all fields unset, using the default string type, if needed
    pub fn new() -> Self {
        VideoDataBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<S: BosStr> VideoDataBuilder<video_data_state::Empty, S> {
    /// Create a new builder with all fields unset
    pub fn builder() -> Self {
        VideoDataBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> VideoDataBuilder<St, S>
where
    St: video_data_state::State,
    St::AspectRatio: video_data_state::IsUnset,
{
    /// Set the `aspectRatio` field (required)
    pub fn aspect_ratio(
        mut self,
        value: impl Into<get_blob_metadata::AspectRatio<S>>,
    ) -> VideoDataBuilder<video_data_state::SetAspectRatio<St>, S> {
        self._fields.0 = Option::Some(value.into());
        VideoDataBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> VideoDataBuilder<St, S>
where
    St: video_data_state::State,
    St::DurationMs: video_data_state::IsUnset,
{
    /// Set the `durationMs` field (required)
    pub fn duration_ms(
        mut self,
        value: impl Into<i64>,
    ) -> VideoDataBuilder<video_data_state::SetDurationMs<St>, S> {
        self._fields.1 = Option::Some(value.into());
        VideoDataBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _type: PhantomData,
        }
    }
}

impl<St, S: BosStr> VideoDataBuilder<St, S>
where
    St: video_data_state::State,
    St::AspectRatio: video_data_state::IsSet,
    St::DurationMs: video_data_state::IsSet,
{
    /// Build the final struct.
    pub fn build(self) -> VideoData<S> {
        VideoData {
            aspect_ratio: self._fields.0.unwrap(),
            duration_ms: self._fields.1.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data.
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<SmolStr, Data<S>>,
    ) -> VideoData<S> {
        VideoData {
            aspect_ratio: self._fields.0.unwrap(),
            duration_ms: self._fields.1.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}