[package]
name = "porxie-lexgen"
license = "AGPL-3.0-or-later"
version = "0.0.0"
edition = "2024"

[lints.clippy]
all = "allow"

[lints.rust]
warnings = "allow"
unsafe_code = "forbid"

[features]
dev_blooym = []

[dependencies]
jacquard-common = { git = "https://tangled.org/nonbinary.computer/jacquard", rev = "f08d5d10c63495a2b4b0f6366aa3f7c6d9f3ce80", default-features = false }
jacquard-derive = { git = "https://tangled.org/nonbinary.computer/jacquard", rev = "f08d5d10c63495a2b4b0f6366aa3f7c6d9f3ce80", default-features = false }
jacquard-lexicon = { git = "https://tangled.org/nonbinary.computer/jacquard", rev = "f08d5d10c63495a2b4b0f6366aa3f7c6d9f3ce80", default-features = false }
miette = { version = "7.6.0", default-features = false }
serde = { version = "1.0.228", default-features = false }
thiserror = { version = "2.0.18", default-features = false }
