[package]
name = "porxie-lexgen"
license = "AGPL-3.0-or-later"
version = "0.0.0"
edition = "2024"

[lints.clippy]
all = "allow"

[lints.rust]
warnings = "allow"
unsafe_code = "forbid"

[features]
dev_blooym = []

[dependencies]
jacquard-common = { version = "0.12.1", default-features = false }
jacquard-derive = { version = "0.12.1", default-features = false }
jacquard-lexicon = { version = "0.12.1", default-features = false }
miette = { version = "7.6.0", default-features = false }
serde = { version = "1.0.229", default-features = false }
thiserror = { version = "2.0.20", default-features = false }
