// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.clearBlobCache
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::types::string::Cid;
use jacquard_derive::{IntoStatic, lexicon};
use serde::{Serialize, Deserialize};

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct ClearBlobCache<'a> {
    #[serde(borrow)]
    pub cid: Cid<'a>,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct ClearBlobCacheOutput<'a> {}
/// Response type for dev.blooym.porxie.clearBlobCache
pub struct ClearBlobCacheResponse;
impl jacquard_common::xrpc::XrpcResp for ClearBlobCacheResponse {
    const NSID: &'static str = "dev.blooym.porxie.clearBlobCache";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = ClearBlobCacheOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for ClearBlobCache<'a> {
    const NSID: &'static str = "dev.blooym.porxie.clearBlobCache";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Response = ClearBlobCacheResponse;
}

/// Endpoint type for dev.blooym.porxie.clearBlobCache
pub struct ClearBlobCacheRequest;
impl jacquard_common::xrpc::XrpcEndpoint for ClearBlobCacheRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.clearBlobCache";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Procedure(
        "application/json",
    );
    type Request<'de> = ClearBlobCache<'de>;
    type Response = ClearBlobCacheResponse;
}

pub mod clear_blob_cache_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Cid;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Cid = Unset;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCid<S> {}
    impl<S: State> State for SetCid<S> {
        type Cid = Set<members::cid>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `cid` field
        pub struct cid(());
    }
}

/// Builder for constructing an instance of this type
pub struct ClearBlobCacheBuilder<'a, S: clear_blob_cache_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Cid<'a>>,),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> ClearBlobCache<'a> {
    /// Create a new builder for this type
    pub fn new() -> ClearBlobCacheBuilder<'a, clear_blob_cache_state::Empty> {
        ClearBlobCacheBuilder::new()
    }
}

impl<'a> ClearBlobCacheBuilder<'a, clear_blob_cache_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        ClearBlobCacheBuilder {
            _state: PhantomData,
            _fields: (None,),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ClearBlobCacheBuilder<'a, S>
where
    S: clear_blob_cache_state::State,
    S::Cid: clear_blob_cache_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<Cid<'a>>,
    ) -> ClearBlobCacheBuilder<'a, clear_blob_cache_state::SetCid<S>> {
        self._fields.0 = Option::Some(value.into());
        ClearBlobCacheBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> ClearBlobCacheBuilder<'a, S>
where
    S: clear_blob_cache_state::State,
    S::Cid: clear_blob_cache_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> ClearBlobCache<'a> {
        ClearBlobCache {
            cid: self._fields.0.unwrap(),
            extra_data: Default::default(),
        }
    }
    /// Build the final struct with custom extra_data
    pub fn build_with_data(
        self,
        extra_data: BTreeMap<
            jacquard_common::deps::smol_str::SmolStr,
            jacquard_common::types::value::Data<'a>,
        >,
    ) -> ClearBlobCache<'a> {
        ClearBlobCache {
            cid: self._fields.0.unwrap(),
            extra_data: Some(extra_data),
        }
    }
}