// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.getBlob
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::deps::bytes::Bytes;
use jacquard_common::types::string::{Did, Cid};
use jacquard_derive::{IntoStatic, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetBlob<'a> {
    #[serde(borrow)]
    pub cid: Cid<'a>,
    #[serde(borrow)]
    pub did: Did<'a>,
}


#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetBlobOutput {
    pub body: Bytes,
}


#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic
)]

#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum GetBlobError<'a> {
    #[serde(rename = "BlobCidMismatch")]
    BlobCidMismatch(Option<CowStr<'a>>),
    #[serde(rename = "BlobFetchFailed")]
    BlobFetchFailed(Option<CowStr<'a>>),
    #[serde(rename = "BlobForbiddenType")]
    BlobForbiddenType(Option<CowStr<'a>>),
    #[serde(rename = "BlobNotFound")]
    BlobNotFound(Option<CowStr<'a>>),
    #[serde(rename = "BlobTooLarge")]
    BlobTooLarge(Option<CowStr<'a>>),
    #[serde(rename = "CannotResolve")]
    CannotResolve(Option<CowStr<'a>>),
    #[serde(rename = "CidUnsupported")]
    CidUnsupported(Option<CowStr<'a>>),
    #[serde(rename = "InternalServerError")]
    InternalServerError(Option<CowStr<'a>>),
    #[serde(rename = "PolicyForbidden")]
    PolicyForbidden(Option<CowStr<'a>>),
}

impl core::fmt::Display for GetBlobError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::BlobCidMismatch(msg) => {
                write!(f, "BlobCidMismatch")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobFetchFailed(msg) => {
                write!(f, "BlobFetchFailed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobForbiddenType(msg) => {
                write!(f, "BlobForbiddenType")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobNotFound(msg) => {
                write!(f, "BlobNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobTooLarge(msg) => {
                write!(f, "BlobTooLarge")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::CannotResolve(msg) => {
                write!(f, "CannotResolve")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::CidUnsupported(msg) => {
                write!(f, "CidUnsupported")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::InternalServerError(msg) => {
                write!(f, "InternalServerError")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::PolicyForbidden(msg) => {
                write!(f, "PolicyForbidden")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for dev.blooym.porxie.getBlob
pub struct GetBlobResponse;
impl jacquard_common::xrpc::XrpcResp for GetBlobResponse {
    const NSID: &'static str = "dev.blooym.porxie.getBlob";
    const ENCODING: &'static str = "*/*";
    type Output<'de> = GetBlobOutput;
    type Err<'de> = GetBlobError<'de>;
    fn encode_output(
        output: &Self::Output<'_>,
    ) -> Result<Vec<u8>, jacquard_common::xrpc::EncodeError> {
        Ok(output.body.to_vec())
    }
    fn decode_output<'de>(
        body: &'de [u8],
    ) -> Result<Self::Output<'de>, jacquard_common::error::DecodeError>
    where
        Self::Output<'de>: serde::Deserialize<'de>,
    {
        Ok(GetBlobOutput {
            body: jacquard_common::deps::bytes::Bytes::copy_from_slice(body),
        })
    }
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetBlob<'a> {
    const NSID: &'static str = "dev.blooym.porxie.getBlob";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetBlobResponse;
}

/// Endpoint type for dev.blooym.porxie.getBlob
pub struct GetBlobRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetBlobRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.getBlob";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetBlob<'de>;
    type Response = GetBlobResponse;
}

pub mod get_blob_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Cid;
        type Did;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Cid = Unset;
        type Did = Unset;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCid<S> {}
    impl<S: State> State for SetCid<S> {
        type Cid = Set<members::cid>;
        type Did = S::Did;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Cid = S::Cid;
        type Did = Set<members::did>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `cid` field
        pub struct cid(());
        ///Marker type for the `did` field
        pub struct did(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetBlobBuilder<'a, S: get_blob_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Cid<'a>>, Option<Did<'a>>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> GetBlob<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetBlobBuilder<'a, get_blob_state::Empty> {
        GetBlobBuilder::new()
    }
}

impl<'a> GetBlobBuilder<'a, get_blob_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetBlobBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobBuilder<'a, S>
where
    S: get_blob_state::State,
    S::Cid: get_blob_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<Cid<'a>>,
    ) -> GetBlobBuilder<'a, get_blob_state::SetCid<S>> {
        self._fields.0 = Option::Some(value.into());
        GetBlobBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobBuilder<'a, S>
where
    S: get_blob_state::State,
    S::Did: get_blob_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<'a>>,
    ) -> GetBlobBuilder<'a, get_blob_state::SetDid<S>> {
        self._fields.1 = Option::Some(value.into());
        GetBlobBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobBuilder<'a, S>
where
    S: get_blob_state::State,
    S::Cid: get_blob_state::IsSet,
    S::Did: get_blob_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetBlob<'a> {
        GetBlob {
            cid: self._fields.0.unwrap(),
            did: self._fields.1.unwrap(),
        }
    }
}