// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.getBlobPolicy
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;

#[allow(unused_imports)]
use jacquard_common::deps::codegen::unicode_segmentation::UnicodeSegmentation;
use jacquard_common::types::string::{Did, Cid};
use jacquard_derive::{IntoStatic, lexicon, open_union};
use jacquard_lexicon::lexicon::LexiconDoc;
use jacquard_lexicon::schema::LexiconSchema;

#[allow(unused_imports)]
use jacquard_lexicon::validation::{ConstraintError, ValidationPath};
use serde::{Serialize, Deserialize};
use crate::dev_blooym::porxie::get_blob_policy;
/// Blob is allowed to be served.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct Allowed<'a> {}

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetBlobPolicy<'a> {
    #[serde(borrow)]
    pub cid: Cid<'a>,
    #[serde(borrow)]
    pub did: Did<'a>,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetBlobPolicyOutput<'a> {
    #[serde(borrow)]
    pub policy: GetBlobPolicyOutputPolicy<'a>,
}


#[open_union]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(tag = "$type", bound(deserialize = "'de: 'a"))]
pub enum GetBlobPolicyOutputPolicy<'a> {
    #[serde(rename = "dev.blooym.porxie.getBlobPolicy#allowed")]
    Allowed(Box<get_blob_policy::Allowed<'a>>),
    #[serde(rename = "dev.blooym.porxie.getBlobPolicy#restricted")]
    Restricted(Box<get_blob_policy::Restricted<'a>>),
    #[serde(rename = "dev.blooym.porxie.getBlobPolicy#unlisted")]
    Unlisted(Box<get_blob_policy::Unlisted<'a>>),
}

/// Blob is explicitly restricted. It may have been removed due to moderation reasons.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct Restricted<'a> {
    ///An optional reason provided for this policy being applied to provide context to the requesting service.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub reason: Option<CowStr<'a>>,
}

/// Blob is not being served at operator discretion. It may not meet the requirements for the service.

#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic, Default)]
#[serde(rename_all = "camelCase")]
pub struct Unlisted<'a> {
    ///An optional reason provided for this policy being applied to provide context to the requesting service.
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub reason: Option<CowStr<'a>>,
}

impl<'a> LexiconSchema for Allowed<'a> {
    fn nsid() -> &'static str {
        "dev.blooym.porxie.getBlobPolicy"
    }
    fn def_name() -> &'static str {
        "allowed"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_dev_blooym_porxie_getBlobPolicy()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

/// Response type for dev.blooym.porxie.getBlobPolicy
pub struct GetBlobPolicyResponse;
impl jacquard_common::xrpc::XrpcResp for GetBlobPolicyResponse {
    const NSID: &'static str = "dev.blooym.porxie.getBlobPolicy";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetBlobPolicyOutput<'de>;
    type Err<'de> = jacquard_common::xrpc::GenericError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetBlobPolicy<'a> {
    const NSID: &'static str = "dev.blooym.porxie.getBlobPolicy";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetBlobPolicyResponse;
}

/// Endpoint type for dev.blooym.porxie.getBlobPolicy
pub struct GetBlobPolicyRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetBlobPolicyRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.getBlobPolicy";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetBlobPolicy<'de>;
    type Response = GetBlobPolicyResponse;
}

impl<'a> LexiconSchema for Restricted<'a> {
    fn nsid() -> &'static str {
        "dev.blooym.porxie.getBlobPolicy"
    }
    fn def_name() -> &'static str {
        "restricted"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_dev_blooym_porxie_getBlobPolicy()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

impl<'a> LexiconSchema for Unlisted<'a> {
    fn nsid() -> &'static str {
        "dev.blooym.porxie.getBlobPolicy"
    }
    fn def_name() -> &'static str {
        "unlisted"
    }
    fn lexicon_doc() -> LexiconDoc<'static> {
        lexicon_doc_dev_blooym_porxie_getBlobPolicy()
    }
    fn validate(&self) -> Result<(), ConstraintError> {
        Ok(())
    }
}

fn lexicon_doc_dev_blooym_porxie_getBlobPolicy() -> LexiconDoc<'static> {
    #[allow(unused_imports)]
    use jacquard_common::{CowStr, deps::smol_str::SmolStr, types::blob::MimeType};
    use jacquard_lexicon::lexicon::*;
    use alloc::collections::BTreeMap;
    LexiconDoc {
        lexicon: Lexicon::Lexicon1,
        id: CowStr::new_static("dev.blooym.porxie.getBlobPolicy"),
        defs: {
            let mut map = BTreeMap::new();
            map.insert(
                SmolStr::new_static("allowed"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static("Blob is allowed to be served."),
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("main"),
                LexUserType::XrpcQuery(LexXrpcQuery {
                    parameters: Some(
                        LexXrpcQueryParameter::Params(LexXrpcParameters {
                            required: Some(
                                vec![SmolStr::new_static("did"), SmolStr::new_static("cid")],
                            ),
                            properties: {
                                #[allow(unused_mut)]
                                let mut map = BTreeMap::new();
                                map.insert(
                                    SmolStr::new_static("cid"),
                                    LexXrpcParametersProperty::String(LexString {
                                        description: Some(
                                            CowStr::new_static("The CID of the blob."),
                                        ),
                                        format: Some(LexStringFormat::Cid),
                                        ..Default::default()
                                    }),
                                );
                                map.insert(
                                    SmolStr::new_static("did"),
                                    LexXrpcParametersProperty::String(LexString {
                                        description: Some(
                                            CowStr::new_static("The DID of the account."),
                                        ),
                                        format: Some(LexStringFormat::Did),
                                        ..Default::default()
                                    }),
                                );
                                map
                            },
                            ..Default::default()
                        }),
                    ),
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("restricted"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "Blob is explicitly restricted. It may have been removed due to moderation reasons.",
                        ),
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("reason"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "An optional reason provided for this policy being applied to provide context to the requesting service.",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map.insert(
                SmolStr::new_static("unlisted"),
                LexUserType::Object(LexObject {
                    description: Some(
                        CowStr::new_static(
                            "Blob is not being served at operator discretion. It may not meet the requirements for the service.",
                        ),
                    ),
                    properties: {
                        #[allow(unused_mut)]
                        let mut map = BTreeMap::new();
                        map.insert(
                            SmolStr::new_static("reason"),
                            LexObjectProperty::String(LexString {
                                description: Some(
                                    CowStr::new_static(
                                        "An optional reason provided for this policy being applied to provide context to the requesting service.",
                                    ),
                                ),
                                ..Default::default()
                            }),
                        );
                        map
                    },
                    ..Default::default()
                }),
            );
            map
        },
        ..Default::default()
    }
}

pub mod get_blob_policy_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
        type Cid;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
        type Cid = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Did = Set<members::did>;
        type Cid = S::Cid;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCid<S> {}
    impl<S: State> State for SetCid<S> {
        type Did = S::Did;
        type Cid = Set<members::cid>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
        ///Marker type for the `cid` field
        pub struct cid(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetBlobPolicyBuilder<'a, S: get_blob_policy_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Cid<'a>>, Option<Did<'a>>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> GetBlobPolicy<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetBlobPolicyBuilder<'a, get_blob_policy_state::Empty> {
        GetBlobPolicyBuilder::new()
    }
}

impl<'a> GetBlobPolicyBuilder<'a, get_blob_policy_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetBlobPolicyBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobPolicyBuilder<'a, S>
where
    S: get_blob_policy_state::State,
    S::Cid: get_blob_policy_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<Cid<'a>>,
    ) -> GetBlobPolicyBuilder<'a, get_blob_policy_state::SetCid<S>> {
        self._fields.0 = Option::Some(value.into());
        GetBlobPolicyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobPolicyBuilder<'a, S>
where
    S: get_blob_policy_state::State,
    S::Did: get_blob_policy_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<'a>>,
    ) -> GetBlobPolicyBuilder<'a, get_blob_policy_state::SetDid<S>> {
        self._fields.1 = Option::Some(value.into());
        GetBlobPolicyBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobPolicyBuilder<'a, S>
where
    S: get_blob_policy_state::State,
    S::Did: get_blob_policy_state::IsSet,
    S::Cid: get_blob_policy_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetBlobPolicy<'a> {
        GetBlobPolicy {
            cid: self._fields.0.unwrap(),
            did: self._fields.1.unwrap(),
        }
    }
}