// @generated by jacquard-lexicon. DO NOT EDIT.
//
// Lexicon: dev.blooym.porxie.getBlobMetadata
//
// This file was automatically generated from Lexicon schemas.
// Any manual changes will be overwritten on the next regeneration.

#[allow(unused_imports)]
use alloc::collections::BTreeMap;

#[allow(unused_imports)]
use core::marker::PhantomData;
use jacquard_common::CowStr;
use jacquard_common::types::string::{Did, Cid};
use jacquard_derive::{IntoStatic, lexicon, open_union};
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetBlobMetadata<'a> {
    #[serde(borrow)]
    pub cid: Cid<'a>,
    #[serde(borrow)]
    pub did: Did<'a>,
}


#[lexicon]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, IntoStatic)]
#[serde(rename_all = "camelCase")]
pub struct GetBlobMetadataOutput<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(borrow)]
    pub content_type: Option<CowStr<'a>>,
    pub size: i64,
}


#[open_union]
#[derive(
    Serialize,
    Deserialize,
    Debug,
    Clone,
    PartialEq,
    Eq,
    thiserror::Error,
    miette::Diagnostic,
    IntoStatic
)]

#[serde(tag = "error", content = "message")]
#[serde(bound(deserialize = "'de: 'a"))]
pub enum GetBlobMetadataError<'a> {
    /// The provided CID was malformed or does not conform to specification.
    #[serde(rename = "MalformedCid")]
    MalformedCid(Option<CowStr<'a>>),
    #[serde(rename = "BlobCidMismatch")]
    BlobCidMismatch(Option<CowStr<'a>>),
    #[serde(rename = "BlobFetchFailed")]
    BlobFetchFailed(Option<CowStr<'a>>),
    #[serde(rename = "BlobForbiddenType")]
    BlobForbiddenType(Option<CowStr<'a>>),
    #[serde(rename = "BlobNotFound")]
    BlobNotFound(Option<CowStr<'a>>),
    #[serde(rename = "BlobTooLarge")]
    BlobTooLarge(Option<CowStr<'a>>),
    #[serde(rename = "CannotResolve")]
    CannotResolve(Option<CowStr<'a>>),
    #[serde(rename = "CidUnsupported")]
    CidUnsupported(Option<CowStr<'a>>),
    #[serde(rename = "PolicyForbidden")]
    PolicyForbidden(Option<CowStr<'a>>),
}

impl core::fmt::Display for GetBlobMetadataError<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::MalformedCid(msg) => {
                write!(f, "MalformedCid")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobCidMismatch(msg) => {
                write!(f, "BlobCidMismatch")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobFetchFailed(msg) => {
                write!(f, "BlobFetchFailed")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobForbiddenType(msg) => {
                write!(f, "BlobForbiddenType")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobNotFound(msg) => {
                write!(f, "BlobNotFound")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::BlobTooLarge(msg) => {
                write!(f, "BlobTooLarge")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::CannotResolve(msg) => {
                write!(f, "CannotResolve")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::CidUnsupported(msg) => {
                write!(f, "CidUnsupported")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::PolicyForbidden(msg) => {
                write!(f, "PolicyForbidden")?;
                if let Some(msg) = msg {
                    write!(f, ": {}", msg)?;
                }
                Ok(())
            }
            Self::Unknown(err) => write!(f, "Unknown error: {:?}", err),
        }
    }
}

/// Response type for dev.blooym.porxie.getBlobMetadata
pub struct GetBlobMetadataResponse;
impl jacquard_common::xrpc::XrpcResp for GetBlobMetadataResponse {
    const NSID: &'static str = "dev.blooym.porxie.getBlobMetadata";
    const ENCODING: &'static str = "application/json";
    type Output<'de> = GetBlobMetadataOutput<'de>;
    type Err<'de> = GetBlobMetadataError<'de>;
}

impl<'a> jacquard_common::xrpc::XrpcRequest for GetBlobMetadata<'a> {
    const NSID: &'static str = "dev.blooym.porxie.getBlobMetadata";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Response = GetBlobMetadataResponse;
}

/// Endpoint type for dev.blooym.porxie.getBlobMetadata
pub struct GetBlobMetadataRequest;
impl jacquard_common::xrpc::XrpcEndpoint for GetBlobMetadataRequest {
    const PATH: &'static str = "/xrpc/dev.blooym.porxie.getBlobMetadata";
    const METHOD: jacquard_common::xrpc::XrpcMethod = jacquard_common::xrpc::XrpcMethod::Query;
    type Request<'de> = GetBlobMetadata<'de>;
    type Response = GetBlobMetadataResponse;
}

pub mod get_blob_metadata_state {

    pub use crate::builder_types::{Set, Unset, IsSet, IsUnset};
    #[allow(unused)]
    use ::core::marker::PhantomData;
    mod sealed {
        pub trait Sealed {}
    }
    /// State trait tracking which required fields have been set
    pub trait State: sealed::Sealed {
        type Did;
        type Cid;
    }
    /// Empty state - all required fields are unset
    pub struct Empty(());
    impl sealed::Sealed for Empty {}
    impl State for Empty {
        type Did = Unset;
        type Cid = Unset;
    }
    ///State transition - sets the `did` field to Set
    pub struct SetDid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetDid<S> {}
    impl<S: State> State for SetDid<S> {
        type Did = Set<members::did>;
        type Cid = S::Cid;
    }
    ///State transition - sets the `cid` field to Set
    pub struct SetCid<S: State = Empty>(PhantomData<fn() -> S>);
    impl<S: State> sealed::Sealed for SetCid<S> {}
    impl<S: State> State for SetCid<S> {
        type Did = S::Did;
        type Cid = Set<members::cid>;
    }
    /// Marker types for field names
    #[allow(non_camel_case_types)]
    pub mod members {
        ///Marker type for the `did` field
        pub struct did(());
        ///Marker type for the `cid` field
        pub struct cid(());
    }
}

/// Builder for constructing an instance of this type
pub struct GetBlobMetadataBuilder<'a, S: get_blob_metadata_state::State> {
    _state: PhantomData<fn() -> S>,
    _fields: (Option<Cid<'a>>, Option<Did<'a>>),
    _lifetime: PhantomData<&'a ()>,
}

impl<'a> GetBlobMetadata<'a> {
    /// Create a new builder for this type
    pub fn new() -> GetBlobMetadataBuilder<'a, get_blob_metadata_state::Empty> {
        GetBlobMetadataBuilder::new()
    }
}

impl<'a> GetBlobMetadataBuilder<'a, get_blob_metadata_state::Empty> {
    /// Create a new builder with all fields unset
    pub fn new() -> Self {
        GetBlobMetadataBuilder {
            _state: PhantomData,
            _fields: (None, None),
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobMetadataBuilder<'a, S>
where
    S: get_blob_metadata_state::State,
    S::Cid: get_blob_metadata_state::IsUnset,
{
    /// Set the `cid` field (required)
    pub fn cid(
        mut self,
        value: impl Into<Cid<'a>>,
    ) -> GetBlobMetadataBuilder<'a, get_blob_metadata_state::SetCid<S>> {
        self._fields.0 = Option::Some(value.into());
        GetBlobMetadataBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobMetadataBuilder<'a, S>
where
    S: get_blob_metadata_state::State,
    S::Did: get_blob_metadata_state::IsUnset,
{
    /// Set the `did` field (required)
    pub fn did(
        mut self,
        value: impl Into<Did<'a>>,
    ) -> GetBlobMetadataBuilder<'a, get_blob_metadata_state::SetDid<S>> {
        self._fields.1 = Option::Some(value.into());
        GetBlobMetadataBuilder {
            _state: PhantomData,
            _fields: self._fields,
            _lifetime: PhantomData,
        }
    }
}

impl<'a, S> GetBlobMetadataBuilder<'a, S>
where
    S: get_blob_metadata_state::State,
    S::Did: get_blob_metadata_state::IsSet,
    S::Cid: get_blob_metadata_state::IsSet,
{
    /// Build the final struct
    pub fn build(self) -> GetBlobMetadata<'a> {
        GetBlobMetadata {
            cid: self._fields.0.unwrap(),
            did: self._fields.1.unwrap(),
        }
    }
}