[package]
name = "porxie-mediautil"
license = "AGPL-3.0-or-later"
version = "0.0.0"
edition = "2024"

[features]
# Metadata Parsing
image-metadata = ["image"]
video-metadata = ["nom-exif"]

[dependencies]
bytes = { version = "1.11.1", default-features = false }
image = { version = "0.25.10", optional = true, default-features = false, features = [
    "avif",
    "gif",
    "ico",
    "jpeg",
    "png",
    "webp",
] }
infer = { version = "0.19.0", default-features = false, features = ["std"] }
log = { version = "0.4.29", default-features = false }
mime = { version = "0.3.17", default-features = false }
nom-exif = { version = "3.4.0", optional = true, default-features = false, features = [
    "tokio",
] }
thiserror = { version = "2.0.18", default-features = false, features = ["std"] }
