name: "Publish to DockerHub"

concurrency:
  group: ${{ github.repository }}-${{github.ref_name}}
  cancel-in-progress: true

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
    with:
      output: image
      platforms: linux/amd64,linux/arm64
      distribute: true
      meta-images: ${{ vars.DOCKERHUB_USERNAME }}/porxie
      push: true
      meta-tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=raw,value=latest,enable=${{ !contains(github.ref_name, '-') }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
